### ISSUE TITLE
When to use records - As intermediate objects example

### ISSUE THREAD

**Issue by alansegar** [grubeninspekteur/New_features_in_Java_9-17#3]
Firstly, thank you for creating this excellent course. It is very much appreciated.

I'm trying to understand the example in _When to use records - As intermediate objects_

https://github.com/grubeninspekteur/New_features_in_Java_9-17/blob/4d7ba044f1fffcca8059aa5f4c5f52034729a48d/Records/Defining%20and%20using%20records/When%20to%20use%20records/task.md?plain=1#L72-L88

I've managed to get it to compile by adding 2 missing closing brackets `))` and a `return`, moving the record outside the method and changing the return type to `Map<String, List<CityPrice>>`, but that leaves me unclear on what the purpose of the intermediate object is. 

```java
    record CityPrice(String city, int price) {}

    Map<String, List<CityPrice>> findTopNPriciestHousesPerCity(int n) {

        return getHouses().stream()
                .map(house -> new CityPrice(house.getCity(), house.getPrice()))
                .distinct()
                .sorted(Comparator.comparing(CityPrice::price).reversed())
                .collect(Collectors.groupingBy(CityPrice::city,
                                Collectors.collectingAndThen(
                                        Collectors.toList(),
                                        prices -> prices.stream()
                                                .limit(n)
                                                .collect(Collectors.toList())
                                )
                        )
                );
    }
```

As it's intended to be intermediate (only used within the method) then I'm assuming it shouldn't be part of the return type, but for the example to return `Map<String, List<House>>` I can't see how the intermediate type would be used / necessary (the line ` .map(house -> new CityPrice(house.getCity(), house.getPrice()))` could be removed and the city and price fields from `House` used directly).

In a scenario where the operations within the method are impossible on the input object (`House`), I can see how an intermediate object could help, but then some additional logic would be needed to convert back from the intermediate object to the input object (used in the return type).

Example without the intermediate object:
```java
    Map<String, List<House>> findTopNPriciestHousesPerCity(int n) {

        return getHouses().stream()
//                .map(house -> new CityPrice(house.getCity(), house.getPrice()))
                .distinct()
                .sorted(Comparator.comparing(House::getPrice).reversed())
                .collect(Collectors.groupingBy(House::getCity,
                                Collectors.collectingAndThen(
                                        Collectors.toList(),
                                        prices -> prices.stream()
                                                .limit(n)
                                                .collect(Collectors.toList())
                                )
                        )
                );
    }
```

**Comment by grubeninspekteur** [comment]
You're right, it's not a good example. I'll follow the one in [JEP 395](https://openjdk.org/jeps/395) which involves an expensive intermediate computation.

**Comment by alansegar** [comment]
Thanks for updating this. Your new example is great.
