### ISSUE TITLE
BonyFish vs. BonelessFish in Sealed Classes - Labeling the subclass

### ISSUE THREAD

**Issue by alansegar** [grubeninspekteur/New_features_in_Java_9-17#4]
https://github.com/grubeninspekteur/New_features_in_Java_9-17/blob/4d7ba044f1fffcca8059aa5f4c5f52034729a48d/Sealed%20Interfaces%20and%20Classes/Defining%20sealed%20interfaces%20and%20classes/Labeling%20the%20subclass/task.md?plain=1#L39

refers to `BonyFish` but the diagram above it contains `BonelessFish` instead.
Are these supposed to match?

**Comment by grubeninspekteur** [comment]
Thanks for the report, indeed they were supposed to match the [Osteichthyes](https://en.wikipedia.org/wiki/Osteichthyes) class of fish.
